### ISSUE TITLE
VMware Workstation 12.5 crashes with gtk3-nocsd

### ISSUE THREAD

**Issue by rod-stuchi** [PCMan/gtk3-nocsd#22]
Took me a while to discover where this error come from.

Steps the to reproduce

> git clone https://github.com/PCMan/gtk3-nocsd.git .
> make 

> **./gtk3-nocsd vmware**

```
Gtk-Message: Failed to load module "canberra-gtk-module": libcanberra-gtk-module.so: cannot open shared object file: No such file or directory
/usr/bin/vmware: line 106:  6444 Segmentation fault      (core dumped) "$BINDIR"/vmware-modconfig --appname="VMware Workstation" --icon="vmware-workstation"

```

running just **vmware**, still get this _libcanberra_ failed load module, but works.

**Comment by rijenkii** [comment]
Actually, it's a `vmware-modconfig` causes the problem
```
gdb --args /usr/lib/vmware/bin/vmware-modconfig --launcher=/usr/bin/vmware-modconfig --appname=VMware Workstation --icon=vmware-workstation 
                                                                     
GNU gdb (GDB) 7.12

...

Reading symbols from /usr/lib/vmware/bin/vmware-modconfig...(no debugging symbols found)...done.

(gdb) run
Starting program: /usr/lib/vmware/bin/vmware-modconfig --launcher=/usr/bin/vmware-modconfig --appname=VMware Workstation --icon=vmware-workstation
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Gtk-Message: Failed to load module "canberra-gtk-module": libcanberra-gtk-module.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7bd4a98 in g_object_get () from /usr/lib/libgtk3-nocsd.so.0
#2  0x00007ffff1499205 in gtk_rc_context_get (settings=0x555555906040) at gtkrc.c:690
#3  0x00007ffff149eaa8 in IA__gtk_rc_reparse_all_for_settings (settings=0x555555906040, force_load=1) at gtkrc.c:1756
#4  0x00007ffff14bb75e in IA__gtk_settings_get_for_screen (screen=0x555555859b20) at gtksettings.c:1066
#5  0x00007ffff1425ea7 in IA__gtk_icon_theme_set_screen (icon_theme=0x55555585e0c0, screen=0x555555859b20) at gtkicontheme.c:505
#6  0x00007ffff14271f9 in IA__gtk_icon_theme_get_for_screen (screen=0x555555859b20) at gtkicontheme.c:326
#7  0x00007ffff08acda6 in Gtk::IconTheme::get_default () at icontheme.cc:272
#8  0x00007fffec04c298 in modconfig::RegisterIcons() () from /usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so
#9  0x00007fffec04c428 in modconfig::Startup(Glib::ustring const&, Glib::ustring const&) () from /usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so
#10 0x00007fffec0410e0 in main () from /usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so
#11 0x000055555556a887 in main ()
```
