### ISSUE TITLE
Segfault when running libc.so.6

### ISSUE THREAD

**Issue by eigengrau** [PCMan/gtk3-nocsd#23]
I’ve noticed that when running `libc.so.6` as a program (which is supposed to output version information for glibc), the process will segfault when libgtk3-nocsd.so is pulled in via `LD_PRELOAD`. Can you advise whether this is expected or perhaps something the GNU folks should be informed about (possible bug in ld-linux)?

Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555556731e7 in _dl_vdso_vsym ()
>>> bt
#0  0x00005555556731e7 in _dl_vdso_vsym ()
#1  0x00005555555fc6b7 in gettimeofday ()
#2  0x00007ffff7de6020 in _dl_relocate_object () from /usr/lib/ld-linux-x86-64.so.2
#3  0x00007ffff7ddd9b1 in dl_main () from /usr/lib/ld-linux-x86-64.so.2
#4  0x00007ffff7df14ef in _dl_sysdep_start () from /usr/lib/ld-linux-x86-64.so.2
#5  0x00007ffff7ddedf8 in _dl_start () from /usr/lib/ld-linux-x86-64.so.2
#6  0x00007ffff7ddad78 in _start () from /usr/lib/ld-linux-x86-64.so.2
#7  0x0000000000000001 in ?? ()
#8  0x00007fffffffe0c3 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by chris-se** [comment]
Interesting, I can confirm that, and will take a look. It's definitely not expected, but I'm not exactly sure what the problem is yet, since I can run libc.so.6 when preloading other trivial libraries, so it's probably not a bug in the GNU tools. Let me get back to you on that.
